idf_component_register(
    SRCS
        "main.cpp"
        "configuration_storage.cpp"
        "display.cpp"
         "reminder_engine.cpp"
        "config_parser.cpp"
        "bluetooth.cpp"
        "rtc_ds3231.cpp"
         "pomodoro.cpp"
        "acknowledgement_input.cpp"
        "audio_manager.cpp"
        "dfplayer.cpp"
        "hx711.cpp"
        "scale.cpp"
        "bottle_calibration.cpp"
        "consumption_tracker.cpp"
       "user_statistics.cpp"
       "statistics_history.cpp"
       "action_log.cpp"
        "wifi_manager.cpp"
        "ota_manager.cpp"

    INCLUDE_DIRS
        "."

    REQUIRES
        esp_driver_spi
        esp_driver_uart
        esp_lcd
        esp_timer
        driver
         bt
        nvs_flash
        spiffs
         esp_wifi
        esp_event
        esp_netif
        esp_http_client
        esp_https_ota
        app_update
        mbedtls
        espressif__cjson
        
)

target_include_directories(
    ${COMPONENT_LIB}
    PRIVATE
        ../components/LovyanGFX/src
)